PHOTO = {
	"agreement": "AgACAgIAAxkBAAMjYW252NTrIECFnE1z_uJ0WVoDTxMAAo-_MRv2WXBLik_5BtyYw9oBAAMCAAN5AAMhBA", 
	"info": "AgACAgIAAxkBAAIfemG1AAHT814qQiNYM27l7Ajw5dWycAACAboxG6Q8qElku6SEknysfAEAAwIAA3kAAyME",
	"support": "AgACAgIAAxkBAAIffGG1AAHxlYig5A39qjUY6gimHEm7mQACAroxG6Q8qEnAjnLpnHdIgQEAAwIAA3kAAyME",
	"price": "AgACAgIAAxkBAAIhyGHIOp4hiBpOywMtebCOCPaEn2eMAAJ8tTEbL_xISmZ8e2i6QO_QAQADAgADeQADIwQ",
	"bank": "AgACAgIAAxkBAAIfcmG1AAEbHruFaxHqFw9p2IQx_aE-mwAC-7kxG6Q8qEn-YYegBWywhAEAAwIAA3kAAyME",
	"raccoon": "AgACAgIAAxkBAAI3U2H3ho10OZ6Yq6yGdd6SuJuhARLIAALgvTEb9LzBS50B1HzxYVHxAQADAgADeQADIwQ"
}


PHOTO_ADMIN = {
	"moderation": "AgACAgIAAxkBAAIhymHIO03mJHF66MhWbhZWLWDRfszkAAJ-tTEbL_xISs_D39Ou_rZ7AQADAgADeQADIwQ",
	"publication_rules": "AgACAgIAAxkBAAIht2HGAXFhSDp_ExQeuV2-7aVDai3uAAJHuDEbpwsxSkG5ctx8P6cBAQADAgADeQADIwQ",
	"stat": "AgACAgIAAxkBAAIfdmG1AAFm6BqCD54bTr0fEa072gjPoQAC_7kxG6Q8qEmmeSb0rujFJgEAAwIAA3kAAyME",
	"console": "AgACAgIAAxkBAAIfeGG1AAGGw7EuVrH_-IMEjVPFGIMMIgADujEbpDyoSSc6z4ecyvYtAQADAgADeQADIwQ"
}