PHOTO = {
	"agreement": "AgACAgIAAxkBAAMjYW252NTrIECFnE1z_uJ0WVoDTxMAAo-_MRv2WXBLik_5BtyYw9oBAAMCAAN5AAMhBA", 
	"info": "AgACAgIAAxkBAAIfemG1AAHT814qQiNYM27l7Ajw5dWycAACAboxG6Q8qElku6SEknysfAEAAwIAA3kAAyME",
	"support": "AgACAgIAAxkBAAIffGG1AAHxlYig5A39qjUY6gimHEm7mQACAroxG6Q8qEnAjnLpnHdIgQEAAwIAA3kAAyME",
	"price": "AgACAgIAAxkBAAMmYW25_xgZB9BprK4op8oaoQx4800AAom_MRv2WXBLgM-opcI31EcBAAMCAAN5AAMhBA",
	"bank": "AgACAgIAAxkBAAIfcmG1AAEbHruFaxHqFw9p2IQx_aE-mwAC-7kxG6Q8qEn-YYegBWywhAEAAwIAA3kAAyME",
	"stat": "AgACAgIAAxkBAAIfdmG1AAFm6BqCD54bTr0fEa072gjPoQAC_7kxG6Q8qEmmeSb0rujFJgEAAwIAA3kAAyME",
	"console": "AgACAgIAAxkBAAIfeGG1AAGGw7EuVrH_-IMEjVPFGIMMIgADujEbpDyoSSc6z4ecyvYtAQADAgADeQADIwQ",
	"moderation": "AgACAgIAAxkBAAIfemG1AAHT814qQiNYM27l7Ajw5dWycAACAboxG6Q8qElku6SEknysfAEAAwIAA3kAAyME"
}